services:
  imusic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imusic
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////app/data/data.db
    volumes:
      - imusic-data:/app/data
    restart: unless-stopped

volumes:
  imusic-data:
